// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0e75f929-2dca-48ba-ae1f-4d97f7607f54",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6ZCEwTFy3",
    "aws_user_pools_web_client_id": "4t00fk53ao70mi8h4ieqdke564",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rtrylfgqavcallijq3e4qofqle.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "29a2967f30d8407b8ce45730ec50b72c",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
